### DISCUSSION TITLE
Dynamically running a dbt package for 2+ distinct sources and outputting to separate schemas

### DISCUSSION THREAD

**Discussion by fivetran-joemarkiewicz** [dbt-labs/devhub-writing#92] [General]
# Overview
For a number of the Fivetran dbt packages, we have added the ability for the packages to union multiple schemas together as this seemed to be a high request from users. Additionally, if the package does not have that ability I will usually direct them to the [Montreal Analytics post](https://blog.montrealanalytics.com/how-to-use-the-shopify-dbt-package-by-fivetran-with-multiple-shops-eb4cea326ee0) on doing this pre-package. However, I have come across a number of users of the Fivetran dbt packages that do not want to union the data and instead have the package models dynamically run once on one source and then on another source and output to two separate schemas.

Recently, I have been seeing this request more and more. I _somewhat_ have an approach for this scenario, but I am not sure if there is a more "dbt-esque" way to accomplish the same result. I wanted to start this discussion to see if others have wanted a similar result of having the same models output to different schemas, if my approach is accurate, and if it is accurate should there be a "Guides and Playbooks" post written about how to do this with dbt package models? Interested to hear everyones opinions on this matter!

# My Suggestion
A recent communication of mine detailing this solution can be seen in [this](https://getdbt.slack.com/archives/C01D1R2JLLA/p1645735148574579) dbt slack post thread. Essentially, I instruct the individuals to leverage a combination of the dbt custom schema config, and our package schema variables to achieve the results they are looking for.

By adding a conditional to their `models` config for the custom schemas we can get the custom schema to dynamically change based off the schema variable.
```yml
models:
  quickbooks:
    +schema: "{% if var('quickbooks_schema','quickbooks') == 'quickbooks_canada' %}quickbooks_canada{% else %}quickbooks_us{% endif %}"
  quickbooks_source:
    +schema: "{% if var('quickbooks_schema','quickbooks') == 'quickbooks_canada' %}quickbooks_canada{% else %}quickbooks_us{% endif %}"
```
Then within their `dbt run` command they can specify the schema variable to ensure the outputs are written to the appropriate custom schema.
```bash
dbt run --vars '{quickbooks_schema: "quickbooks_canda"}'
```

The output of this run command would then be something along the lines of `ca_qb_quickbooks_canada`. Similarly, if they perform a subsequent run with `quickbooks_us` as the variable, the output would be `us_qb_quickbooks_us`

# Closing Thoughts
I am hoping there is a much more elegant and simple way to achieve this result. Further, I am unsure how this can be accomplished with other packages that do not leverage the same schema and database variables? I am happy to speak more to this scenario if needed.
